### ISSUE TITLE
Cannot basecall squigulator reads

### ISSUE THREAD

**Issue by maximilianmordig** [Psy-Fer/buttery-eel#56]
Hi
I cannot basecall squigulator reads. I run
```
squigulator -t "$(nproc)" --seed 1 -o reads.blow5 -n 100 \
    -c "gt_alignment.paf" \
    --verbose 10 \
    -t $(nproc) \
    --ont-friendly=yes \
    pre_input/ref.fa

buttery_eel -g "$(dirname $(which dorado))" --config dna_r9.4.1_450bps_hac.cfg --device auto -i reads.blow5 -o reads.fastq --port auto
```
I get 
```
An exception occurred in stage 3: KeyError - 'protocol_group_id'
```
for all reads. Probably, ONT changed its standard again.

Version info:
```
squigulator --version; buttery_eel --version; dorado --version
squigulator 0.4.0
buttery-eel - wrapping ONT basecallers (guppy/dorado) for SLOW5 basecalling version: 0.5.0
[2024-10-14 10:31:10.970] [info] Running: "--version"
0.6.2+29f311b
```

In the meantime, is there a tool to convert slow5 directly to pod5 without converting to fast5 first?

Another question: Shouldn't `--trim_adapters` be enabled by default because most users want to align reads afterwards?

**Comment by Psy-Fer** [comment]
Hey,

I just pushed a change to main, v0.5.2, that should resolve the error.
Let me know if you run into any others.

Yes there is a tool called blue-crab that I wrote to convert between pod5 and slow5
https://github.com/Psy-Fer/blue-crab

In long reads adapters will get clipped, so it's not really a big deal. If you are assembling, then yes, you 100% want to trim adapters. 

While demultiplexing is included in buttery-eel, I tend to prefer the pipelining approach to bioinformatics rather than the 1 tool to do 10 things, i'd rather 10 tools that does each thing really well, with a few options for each tool, that you can pipeline together for the exact outcome you want, with the ability to re-run the pipeline from any stage. That's a personal preference, so I included the trimming in. However you can always use guppy_barcoder/dorado_barcoder (or whatever it's called now), to demux/trim barcodes or adapters.

James

**Comment by maximilianmordig** [comment]
Hi James
Thanks for the answers. It works now.

**Comment by Psy-Fer** [comment]
Great 👍 

Let me know if you have any other issues.

James
